# Generated by Django 2.2 on 2021-04-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('user text', 'ответ текстом'), ('single choice', 'ответ с выбором одного варианта'), ('multi choice', 'ответ с выбором нескольких вариантов')], max_length=120, verbose_name='Тип вопроса'),
        ),
    ]
